# Generated by Django 3.2.4 on 2021-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AddField(
            model_name='person',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='upi',
            field=models.CharField(default='', max_length=10),
        ),
    ]
